
spring:
  application:
    name:
      notification-service
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/product-service?authSource=admin

# docker exec -it mongodb mongosh
# use admin
# show users?
# db.createUser(

api:
  prefix: /api/v1

server:
  port: 8081


